export const EPIC_USERNAME = process.env.EPIC_USERNAME;
export const EPIC_PASSWORD = process.env.EPIC_PASSWORD;
export const EPIC_AUTHORIZATION = process.env.EPIC_AUTHORIZATION || 'MzRhMDJjZjhmNDQxNGUyOWIxNTkyMTg3NmRhMzZmOWE6ZGFhZmJjY2M3Mzc3NDUwMzlkZmZlNTNkOTRmYzc2Y2Y=';
export const FORTNITE_AUTHORIZATION = process.env.FORTNITE_AUTHORIZATION || 'ZWM2ODRiOGM2ODdmNDc5ZmFkZWEzY2IyYWQ4M2Y1YzY6ZTFmMzFjMjExZjI4NDEzMTg2MjYyZDM3YTEzZmM4NGQ=';
